cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.card, name='card'),
    path('add_cart/<int:id>', views.add_cart, name='add_cart'),
    path('remove_cart/<int:id>', views.remove_cart, name='remove_cart'),
    path('add_quantity/<int:id>', views.add_quantity, name='add_quantity'),
    path('remove_quantity/<int:id>', views.remove_quantity, name='remove_quantity'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('<int:order_id>/', views.order, name='order'),
    path('create_order/', views.create_order, name='create_order'),
    path('coupon/<int:order_id>', views.coupon, name='coupon'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls', namespace='home')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('order/', include('order.urls', namespace='order'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.
                                                                                           MEDIA_ROOT)

cart/models.py
from django.db import models
from django.forms import ModelForm
from home.models import *


class Card(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.PositiveIntegerField()


class CardForm(ModelForm):
    class Meta:
        model = Card
        fields = ['quantity']

cart/views.py
from django.shortcuts import render, redirect
from .models import *
from order.models import OrderForm


def card(request):
    card_ = Card.objects.filter(user_id=request.user.id)
    order = OrderForm()
    total = 0
    for p in card_:
        if p.product.status != 'None':
            total += p.variant.total_price * p.quantity
        else:
            total += p.product.total_price * p.quantity
    return render(request, 'cart/cart.html', {'card': card_, 'total': total, 'order': order})


def add_cart(request, id):
    product = Products.objects.get(id=id)
    if product.status != 'None':
        var_id = request.POST.get('select')
        data = Card.objects.filter(user_id=request.user.id, variant_id=var_id)
        if data:
            check = 'yes'
        else:
            check = 'no'
    else:
        data = Card.objects.filter(user_id=request.user.id, product_id=id)
        if data:
            check = 'yes'
        else:
            check = 'no'
    if request.method == 'POST':
        url = request.META.get('HTTP_REFERER')
        form = CardForm(request.POST)
        var_id = request.POST.get('select')
        if form.is_valid():
            info = form.cleaned_data['quantity']
            if check == 'yes':
                if product.status != 'None':
                    shop = Products.objects.get(user_id=request.user.id, product_id=id, variant_id=var_id)
                else:
                    shop = Products.objects.get(user_id=request.user.id, product_id=id)
                shop.quantity += info
                shop.save()
            else:
                Card.objects.create(user_id=request.user.id, product_id=id, variant_id=var_id, quantity=info)
        return redirect(url)


def remove_cart(request, id):
    url = request.META.get('HTTP_REFERER')
    Card.objects.filter(id=id).delete()
    return redirect(url)


def add_quantity(request, id):
    url = request.META.get('HTTP_REFERER')
    cart = Card.objects.get(id=id)
    if cart.product.status == 'None':
        product = Products.objects.get(id=cart.product.id)
        if product.amount > cart.quantity:
            cart.quantity += 1
    else:
        variant = Variant.objects.get(id=cart.variant.id)
        if variant.amount > cart.quantity:
            cart.quantity += 1
    cart.save()
    return redirect(url)


def remove_quantity(request, id):
    url = request.META.get('HTTP_REFERER')
    cart = Card.objects.get(id=id)
    product = Products.objects.get(id=cart.product.id)
    if cart.quantity > 0:
        cart.quantity -= 1
        cart.save()
    if cart.quantity == 0:
        cart.delete()
    return redirect(url)

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% block body %}
    <div class="container mt-2">
        <table class="table table-dark">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">image</th>
                <th scope="col">product</th>
                <th scope="col">size</th>
                <th scope="col">color</th>
                <th scope="col">price</th>
                <th scope="col">count</th>
                <th scope="col">total price</th>
                <th scope="col">remove</th>
            </tr>
            </thead>
            <tbody>
            {% for c in card %}
                <tr>
                    <th scope="col">{{ forloop.counter }}</th>
                    <td><img src="{{ c.product.image.url }}" style="width: 100px; height: 100px"></td>
                    <td>{{ c.product.name }}</td>
                    <td>{{ c.variant.size }}</td>
                    <td>{{ c.variant.color }}</td>
                    <td>
                        {% if c.product.status != 'None' %}
                            {{ c.variant.total_price }}
                        {% else %}
                            {{ c.product.total_price }}
                        {% endif %}
                    </td>

                    <td>
                        <a href="{% url 'cart:add_quantity' c.id %}"><p>+</p></a>
                        {{ c.quantity }}
                        <a href="{% url 'cart:remove_quantity' c.id %}"><p>-</p></a>
                    </td>
                    <td>
                        {% if c.product.status != 'None' %}
                            {% widthratio c.variant.total_price 1 c.quantity %}
                        {% else %}
                            {% widthratio c.product.total_price 1 c.quantity %}
                        {% endif %}
                    </td>
                    <td><a href="{% url 'cart:remove_cart' c.id %}">remove</a></td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="7">total price:</td>
                <td>{{ total }}</td>
            </tr>
            </tbody>
        </table>
        <div>
            <form method="post" action="{% url 'order:create_order' %}">
                {% csrf_token %}
                {{ order.as_p }}
                <button type="submit">order</button>
            </form>
        </div>
    </div>
{% endblock %}