cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.card, name='card'),
    path('add_cart/<int:id>', views.add_cart, name='add_cart'),
    path('remove_cart/<int:id>', views.remove_cart, name='remove_cart'),
    path('add_quantity/<int:id>', views.add_quantity, name='add_quantity'),
    path('remove_quantity/<int:id>', views.remove_quantity, name='remove_quantity'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('category/<slug>/<int:id>/', views.products, name='category'),
    path('details/<int:id>/', views.products_details, name='products_details'),
    path('like/<int:id>', views.product_like, name='product_like'),
    path('unlike/<int:id>', views.product_unlike, name='product_unlike'),
    path('comment/<int:id>', views.comment, name='comment'),
    path('reply/<int:id>/<int:text_id>', views.comment_reply, name='comment_reply'),
    path('comment_like/<int:id>', views.comment_likes, name='comments_likes'),
    path('search/', views.product_search, name='product_search'),
    path('contact_us/', views.contact_us, name='contact_us'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls', namespace='home')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('order/', include('order.urls', namespace='order'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.
                                                                                           MEDIA_ROOT)

home/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.db.models.signals import post_save


class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='sub')
    sub_cat = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(allow_unicode=True, unique=True, blank=True, null=True)
    image = models.ImageField(upload_to='category', null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:category', args=[self.slug, self.id])


class Products(models.Model):
    VARIANT = (
        ('None', 'none'),
        ('Size', 'size'),
        ('Color', 'color'),
    )
    category = models.ManyToManyField(Category, blank=True)
    name = models.CharField(max_length=200)
    amount = models.PositiveIntegerField()
    unit_price = models.PositiveIntegerField()
    discount = models.PositiveIntegerField(blank=True, null=True)
    change = models.BooleanField(default=False)
    total_price = models.PositiveIntegerField()
    information = RichTextUploadingField(blank=True, null=True)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)
    tags = TaggableManager(blank=True)
    status = models.CharField(max_length=200, null=True, blank=True, choices=VARIANT, default=None)
    image = models.ImageField(upload_to='products')
    like = models.ManyToManyField(User, blank=True, related_name='product_like')
    total_like = models.IntegerField(default=0)
    unlike = models.ManyToManyField(User, blank=True, related_name='product_unlike')
    total_unlike = models.IntegerField(default=0)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE, null=True, blank=True)
    color = models.ManyToManyField('Color', blank=True)
    size = models.ManyToManyField('Size', blank=True)
    views = models.IntegerField(default=0, null=True, blank=True)

    def total_like(self):
        return self.like.count()

    def total_unlike(self):
        return self.unlike.count()

    def __str__(self):
        return self.name

    @property
    def total_price(self):
        if not self.discount:
            return self.unit_price
        if self.discount:
            total = (self.discount * self.unit_price) / 100
            return int(self.unit_price - total)
        return self.total_price


class Size(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Color(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Variant(models.Model):
    name = models.CharField(max_length=200)
    product_variant = models.ForeignKey(Products, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, null=True, blank=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.PositiveIntegerField()
    unit_price = models.PositiveIntegerField()
    discount = models.PositiveIntegerField(blank=True, null=True)
    total_price = models.PositiveIntegerField()

    def __str__(self):
        return self.name

    @property
    def total_price(self):
        if not self.discount:
            return self.unit_price
        if self.discount:
            total = (self.discount * self.unit_price) / 100
            return int(self.unit_price - total)
        return self.total_price


class Comment(models.Model):
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    is_reply = models.BooleanField(default=False)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='comment_reply')
    rate = models.PositiveIntegerField(default=1)
    create = models.DateTimeField(auto_now_add=True)
    comment_like = models.ManyToManyField(User, blank=True, related_name='com_like')
    total_like = models.PositiveIntegerField(default=0)

    def total_like(self):
        return self.comment_like.count()

    def __str__(self):
        return self.product.name


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'rate']


class ReplyForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class Image(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='image_product')
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='image/', blank=True)


class Brand(models.Model):
    brand = models.CharField(max_length=200)

    def __str__(self):
        return self.brand


class Chart(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    unit_price = models.IntegerField(default=0)
    update = models.DateTimeField(auto_now=True)
    size = models.CharField(max_length=200, null=True, blank=True)
    color = models.CharField(max_length=200, null=True, blank=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='up_product', blank=True, null=True)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE, related_name='var_product', blank=True, null=True)

    def __str__(self):
        return self.name


class View (models.Model):
    ip = models.CharField(max_length=200, blank=True, null=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='product')

    def __str__(self):
        return self.product.name


def product_post_saved(sender, instance, created, *args, **kwargs):
    data = instance
    if data.change == True:
        Chart.objects.create(product=data, unit_price=data.unit_price, update=data.update,
                             name=data.name)


post_save.connect(product_post_saved, sender=Products)

home/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(max_length=20)

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import *
from .forms import *
from django.db.models import Q, Max, Min
from cart.models import *
from django.core.mail import EmailMessage
from django.core.paginator import Paginator
from .filters import ProductFilter


def home(request):
    category = Category.objects.filter(sub_cat=False)
    return render(request, 'home/home.html', {'category': category})


def products(request, slug=None, id=None):
    product = Products.objects.all()
    min = Products.objects.aggregate(unit_price=Min('unit_price'))
    min_price = int(min['unit_price'])
    max = Products.objects.aggregate(unit_price=Max('unit_price'))
    max_price = int(max['unit_price'])
    filter_product = ProductFilter(request.GET, queryset=product)
    product = filter_product.qs
    paginator = Paginator(product, 2)
    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)
    search = SearchForm()
    category = Category.objects.filter(sub_cat=False)
    if slug and id:
        data = Category.objects.get(slug=slug, id=id)
        page_obj = Products.objects.filter(category=data)
        paginator = Paginator(page_obj, 2)
        page_num = request.GET.get('page')
        page_obj = paginator.get_page(page_num)

    return render(request, 'home/product.html', {'product': page_obj, 'category': category, 'search': search
        , 'filter': filter_product, 'min': min_price, 'max': max_price})


def products_details(request, id):
    comment_form = CommentForm()
    p_image = Image.objects.filter(product_id=id)
    com_rep = ReplyForm()
    card_form = CardForm()
    product_ = Products.objects.get(id=id)
    comments = Comment.objects.filter(product_id=id, is_reply=False)
    similar = product_.tags.similar_objects()[:2]
    ip = request.META.get('REMOTE_ADDR')
    view = View.objects.filter(product_id=product_.id, ip=ip)
    if not view.exists():
        View.objects.create(ip=ip, product_id=product_.id)
        product_.views += 1
        product_.save()
    is_like = False
    if product_.like.filter(id=request.user.id).exists():
        is_like = True
    else:
        is_like = False
    is_unlike = False
    if product_.unlike.filter(id=request.user.id).exists():
        is_unlike = True
    else:
        is_unlike = False
    if product_.status != 'None':
        if request.method == 'POST':
            variant = Variant.objects.filter(product_variant_id=id)
            var_id = request.POST.get('select')
            variants = Variant.objects.get(id=var_id)
        else:
            variant = Variant.objects.filter(product_variant_id=id)
            variants = Variant.objects.get(id=variant[0].id)
        context = {'product': product_, 'variants': variants, 'variant': variant, 'similar': similar, 'is_like': is_like
            , 'is_unlike': is_unlike, 'comment_form': comment_form, 'comments': comments, 'com_rep': com_rep,
                   'image': p_image, 'card_form': card_form}
        return render(request, 'home/details.html', context)
    else:
        return render(request, 'home/details.html', {'product': product_, 'similar': similar, 'is_like': is_like,
                                                     'is_unlike': is_unlike, 'comment_form': comment_form,
                                                     'comments': comments, 'com_rep': com_rep, 'image': p_image,
                                                     'card_form': card_form})


def product_like(request, id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Products, id=id)
    if product.like.filter(id=request.user.id).exists():
        product.like.remove(request.user)
    else:
        product.like.add(request.user)
        messages.success(request, 'thank you for like', 'success')
    return redirect(url)


def product_unlike(request, id):
    url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Products, id=id)
    if product.unlike.filter(id=request.user.id).exists():
        product.unlike.remove(request.user)
    else:
        product.unlike.add(request.user)
        messages.success(request, 'thank you for unlike', 'success')
    return redirect(url)


def comment(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            data = comment_form.cleaned_data
            Comment.objects.create(text=data['text'], rate=data['rate'], user_id=request.user.id, product_id=id)
        return redirect(url)


def comment_reply(request, id, text_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        reply_form = ReplyForm(request.POST)
        if reply_form.is_valid():
            data = reply_form.cleaned_data
            Comment.objects.create(text=data['text'], product_id=id, reply_id=text_id, user_id=request.user.id,
                                   is_reply=True)
            messages.success(request, 'thanks for reply')
        return redirect(url)


def comment_likes(request, id):
    url = request.META.get('HTTP_REFERER')
    comment_lik = Comment.objects.get(id=id)
    if comment_lik.comment_like.filter(id=request.user.id).exists():
        comment_lik.comment_like.remove(request.user)
    else:
        comment_lik.comment_like.add(request.user)
    return redirect(url)


def product_search(request):
    product = Products.objects.all()
    if request.method == 'POST':
        search = SearchForm(request.POST)
        if search.is_valid():
            data = search.cleaned_data['search']
            if data is not None:
                if data.isdigit():
                    product = product.filter(Q(unit_price=data))
                else:
                    product = product.filter(Q(name__icontains=data))
            return render(request, 'home/product.html', {'product': product, 'search': search})


def contact_us(request):
    if request.method == 'POST':
        name = request.POST['subject']
        email = request.POST['email']
        msg = request.POST['message']
        body = name + '\n' + email + '\n' + msg
        form = EmailMessage(
            'contact us',
            body,
            'test',
            ('nimajavangt@gmail.com',),
        )
        form.send(fail_silently=False)
        messages.success(request, 'thanks for contact us', 'info')
    return render(request, 'home/contact.html')

home/templates/home/contact.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <div class="card bg-dark mt-3 text-white p-5">
            <form method="post" action="{% url 'home:contact_us' %}">
                {% csrf_token %}
                <h1 class="text-center">contact us</h1>
                <div class="row">
                    <div class="col-6">
                        <input type="text" name="subject" class="form-control" placeholder="subject">
                    </div>
                    <div class="col-6">
                        <input type="email" name="email" class="form-control" placeholder="email">
                    </div>
                </div>
                <div class="row mt-3">
                    <textarea type="text" name="message" class="form-control" rows="4" placeholder="your message">
                    </textarea>
                </div>
                <button type="submit" class="btn btn-danger mt-2">send</button>
            </form>
        </div>
    </div>

{% endblock %}

home/templates/home/details.html
{% extends 'base.html' %}
{% block body %}
    <P>{{ product.information|safe }}</P>
    <hr>
    <div>
        {% for img in image %}
            <img src="{{ img.image.url }}" style="height: 200px; width: 200px;" alt="">
        {% endfor %}
    </div>
    {% if product.status == 'Size' %}
        {% for data in variant %}
            <form method="post">
            {% csrf_token %}
            <input type="radio" value="{{ data.id }}" {% if variants.id == data.id %}checked{% endif %}
            name="select" onchange="this.form.submit();">
            <a href="" style="text-decoration: none">{{ data.size }}</a>
            </form>
        {% endfor %}
    {% endif %}

    {% if product.status == 'Color' %}
        {% for data in variant %}
            <form method="post">
            {% csrf_token %}
            <input type="radio" value="{{ data.id }}" {% if variants.id == data.id %}checked{% endif %}
            name="select" onchange="this.form.submit();">
            <a href="" style="text-decoration: none">{{ data.color }}</a>
            </form>
        {% endfor %}
    {% endif %}
    <div class="card bg-danger">
        <p>your choice price: {{ variants.total_price }}</p>
    </div>
    <div class="card col-3">
        {% if product.status != 'None' %}
            <form method="post" action="{% url 'cart:add_cart' product.id %}">
            {% csrf_token %}
            <input type="hidden" name="select" value="{{ variants.id }}">
            <input type="number" name="quantity" min="1" value="1" max="{{ variants.amount }}">
            <button type="submit">Add</button>
        </form>
        {% else %}
            <form method="post" action="{% url 'cart:add_cart' product.id %}">
            {% csrf_token %}
            <input type="number" name="quantity" min="1" value="1" max="{{ product.amount }}">
            <button type="submit">Add</button>
        </form>
        {% endif %}
    </div>
    <hr>

        <small>Like: {{ product.total_like }}</small>
        {% if request.user.is_authenticated %}
            {% if is_like == False %}
                <a href="{% url 'home:product_like' product.id %}" class="btn btn-info
                {% if is_unlike %}disabled{% endif %}">Like</a><br><br>
            {% else %}
                <a href="{% url 'home:product_like' product.id %}" class="btn btn-danger
                {% if is_unlike %}disabled{% endif %}">disLike</a><br><br>
            {% endif %}

            <small>unLike: {{ product.total_unlike }}</small>
            {% if is_unlike == False %}
                <a href="{% url 'home:product_unlike'  product.id %}" class="btn btn-danger
                {% if is_like %}disabled{% endif %}">unlike</a>
            {% else %}
                <a href="{% url 'home:product_unlike' product.id %}" class="btn btn-info
                {% if is_like %}disabled{% endif %}">Like</a>
            {% endif %}

        {% endif %}
    <hr>
    {% for tag in similar %}
        <a href="{% url 'home:products_details' tag.id %}">
            <img src="{{ tag.image.url }}" alt="">
        </a>
    {% endfor %}

    <div class="container card bg-dark text-white mb-2">
    {% for com in comments %}
        <a href="{% url 'home:comments_likes' com.id %}" class="like m-2 cursor">
            Like
        </a>
        {{ com.total_like }}
        <p>{{ com.text }}</p>
        <small>rate: {{ com.rate }}</small>
        <div class="col-4">
            <form method="post" action="{% url 'home:comment_reply' product.id com.id %}">
                {% csrf_token %}
                <textarea name="text" id="text" class="form-control" rows="4" placeholder="Reply....."
                required></textarea>
                <button type="submit">Reply</button>
            </form>
        </div>
        <div>
        {% for data in com.comment_reply.all %}
            <p>{{ data.text }}</p>
        {% endfor %}
        </div>
        <hr>
    {% endfor %}

    </div>
    <div class="card bg-dark text-white col-4 ">
        <form method="post" action="{% url 'home:comment' product.id %}">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit">send</button>
    </form>
    </div>

{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% block title %}
    register
{% endblock title %}
{% block body %}
    {% for cat in category %}
        <h1>{{ cat.name }}</h1>
        <a href="{{ cat.get_absolute_url }}">
            <img src="{{ cat.image.url }}" style="width: 200px; height: 200px" alt="">
        </a>
    {% endfor %}
{% endblock body %}

home/templates/home/product.html
{% extends 'base.html' %}
{% block title %}
    products
{% endblock %}
{% block body %}
    <div class="text-center">
        <form method="post" action="{% url 'home:product_search' %}">
            {% csrf_token %}
            {{ search }}
            <button type="submit">search</button>
        </form>
    </div>

    <div class="mt-2 mb-2">
        {% for cat_1 in category %}
            <a href="{{ cat_1.get_absolute_url }}">{{ cat_1.name }}</a>
            <div class="btn-group">
                <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown"
                        aria-expanded="false">
                </button>
                <ul class="dropdown-menu">
                    {% for cat_2 in cat_1.sub.all %}
                        <li><a class="dropdown-item" href="{{ cat_2.get_absolute_url }}">{{ cat_2.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-3">
            <form method="get" action="">
                <label> price:
                    <input type="range" name="price" min="{{ min }}" max="{{ max }}">
                </label><br><br>
                <label> Brand:
                    {{ filter.form.brand }}
                </label><br>
                <label>color:
                    {{ filter.form.color }}
                </label><br>
                <label>size:
                    {{ filter.form.size }}
                </label><br>
                <button class="btn btn-danger" type="submit">set</button>
            </form>
            <br>

        </div>
        <div class="col-9">
            <div class="container">
                <div class="row">
                    <div>
                        <form action="">
                            <input type="submit" name="price_sort" value="Cheap">
                            <input type="submit" name="price_sort" value="Expensive">
                            <input type="submit" name="time_sort" value="New">
                            <input type="submit" name="like_sort" value="Like">
                            <input type="submit" name="like_sort" value="Like_">
                        </form>
                    </div>
                    {% for cat in product %}
                        <div class="col-3 card">
                            <h1>{{ cat.name }}</h1>
                            <a href={% url 'home:products_details' cat.id %}>
                                <img src="{{ cat.image.url }}" width="200px" height="200px" alt="">
                            </a>
                            <p>{{ cat.unit_price }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                {% if product.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ product.previous_page_number }}">Previous</a></li>
                {% endif %}
                {% if product.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ product.next_page_number }}">Next</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}


<li class="page-item"><a class="page-link" href="#">1</a></li>
<li class="page-item"><a class="page-link" href="#">2</a></li>
<li class="page-item"><a class="page-link" href="#">3</a></li>