accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name='user_update'),
    path('ch_password/', views.change_password, name='change_password'),
    path('login_phone/', views.login_phone, name='login_phone'),
    path('verify_sms/', views.verify_sms, name='verify_sms'),
    path('active/', views.RegisterEmail.as_view(), name='active'),
    path('reset/', views.ResetPassword.as_view(), name='reset'),
    path('reset/done', views.DonePassword.as_view(), name='reset_done'),
    path('confirm/<uidb64>/<token>/', views.ConfirmPassword.as_view(), name='password_reset_done'),
    path('confrim/done/', views.Complete.as_view(), name='complete'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.card, name='card'),
    path('add_cart/<int:id>', views.add_cart, name='add_cart'),
    path('remove_cart/<int:id>', views.remove_cart, name='remove_cart'),
    path('add_quantity/<int:id>', views.add_quantity, name='add_quantity'),
    path('remove_quantity/<int:id>', views.remove_quantity, name='remove_quantity'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls', namespace='home')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('order/', include('order.urls', namespace='order'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.
                                                                                           MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.IntegerField(null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to='profile/', default='1.png')

    def __str__(self):
        return self.user.username


def user_profile(**kwargs):
    if kwargs['created']:
        profile_user = Profile(user=kwargs['instance'])
        profile_user.save()


post_save.connect(user_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class UserRegisterForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    user_name = forms.CharField(max_length=50)
    email = forms.EmailField()
    password_1 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'placeholder': 'enter password'}))
    password_2 = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'placeholder': 'repeat your password'}
                                                                           ))

    def clean_user_name(self):
        user = self.cleaned_data['user_name']
        if User.objects.filter(username=user).exists():
            raise forms.ValidationError('this username is exist')
        return user

    def clean_email(self):
        email_ = self.cleaned_data['email']
        if User.objects.filter(email=email_).exists():
            raise forms.ValidationError('this email is exist')
        return email_

    def clean_password_2(self):
        password_ = self.cleaned_data['password_1']
        password__ = self.cleaned_data['password_2']
        if password_ != password__:
            raise forms.ValidationError('password dose not match')
        elif len(password__) < 8:
            raise forms.ValidationError('password is too short')
        elif not any(x.isupper() for x in password__):
            raise forms.ValidationError('please insert one uppercase')
        else:
            return password_


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}))


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class UpdateUserModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone', 'address', 'image']


class PhoneForm(forms.Form):
    phone = forms.IntegerField()


class VerifyForm(forms.Form):
    code = forms.IntegerField()

accounts/views.py
from django.shortcuts import render, redirect, reverse
from .forms import *
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from kavenegar import *
from random import randint
from django.http import HttpResponse
from django.core.mail import EmailMessage
from django.views import View
from django.utils.encoding import force_str, force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from six import text_type
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


class EmailToken(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return (text_type(user.is_active) + text_type(user.id) + text_type(timestamp))


email_generations = EmailToken()


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(username=data['user_name'], email=data['email'], password=data['password_1']
                                            , first_name=data['first_name'], last_name=data['last_name'])
            user.is_active = False
            user.save()
            domain = get_current_site(request).domain
            uidb64 = urlsafe_base64_encode(force_str(user.id))
            url = reverse('accounts:active', kwargs={'uidb64': uidb64, 'token': email_generations.make_token(user)})
            link = 'http://' + domain + url
            email = EmailMessage(
                'active user',
                link,
                'hi user',
                'test<nimajavangt@gmail.com>',
                [data['email']]
            )
            email.send(fail_silently=False)
            return redirect('home:products')
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, 'accounts/register.html', context)


class RegisterEmail(View):
    def get(self, request, uidb64, token):
        user_id = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=user_id)
        if user and email_generations.check_token(user, token):
            user.is_active = True
            user.save()
            return redirect('accounts:login')


def login_user(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            try:
                user = authenticate(request, username=User.objects.get(email=data['username']),
                                    password=data['password'])
            except:
                user = authenticate(request, username=data['username'], password=data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'login successful')
                return redirect('home:products')
    else:
        form = UserLoginForm

    return render(request, 'accounts/login.html', {'form': form})


def logout_user(request):
    logout(request)
    messages.success(request, 'logout successful')
    return redirect('home:products')


@login_required(login_url='accounts:login')
def user_profile(request):
    profile_ = Profile.objects.get(user_id=request.user.id)
    return render(request, 'accounts/profile.html', {'profile': profile_})


@login_required(login_url='accounts:login')
def user_update(request):
    if request.method == 'POST':
        form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateUserModelForm(request.POST, request.POST, instance=request.user.profile)
        if form and profile_form.is_valid():
            form.save()
            profile_form.save()
            messages.success(request, 'update successfully', 'success')
    else:
        form = UpdateUserForm(instance=request.user)
        profile_form = UpdateUserModelForm(instance=request.user.profile)
    context = {'form': form, 'profile_form': profile_form}
    return render(request, 'accounts/update.html', context)


@login_required(login_url='accounts:login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.POST, request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'successfully', 'success')
        else:
            messages.error(request, 'wrong password', 'danger')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'accounts/password.html', context)


def login_phone(request):
    if request.method == 'POST':
        form = PhoneForm(request.POST)
        if form.is_valid():
            global phone, random_code
            phone = f"0{form.cleaned_data['phone']}"
            random_code = randint(100, 1000)
            api = KavenegarAPI(
                '77634E51555442727237775751353472616B6C61306F5037565169563431326B79697A50434C785A5473413D')
            params = {'sender': '100047778', 'receptor': phone, 'message': random_code}
            response = api.sms_send(params)
            HttpResponse(request, response)
            return redirect('accounts:verify_sms')
    else:
        form = PhoneForm()
    context = {'form': form}
    return render(request, 'accounts/login_phone.html', context)


def verify_sms(request):
    if request.method == 'POST':
        form = VerifyForm()
        if form.is_valid():
            if random_code == form.cleaned_data['code']:
                profile = Profile.objects.get(phone=phone)
                user = User.objects.get(profile__id=profile.id)
                login(request, user)
                messages.success(request, 'you are login successful')
                return redirect('accounts:profile')
            else:
                messages.error(request, 'code is wrong')
    else:
        form = VerifyForm()
    context = {'form': form}
    return render(request, 'accounts/verify_sms.html', context)


class ResetPassword(auth_views.PasswordResetView):
    template_name = 'accounts/reset.html'
    success_url = reverse_lazy('accounts:reset_done')
    email_template_name = 'accounts/link.html'


class DonePassword(auth_views.PasswordResetDoneView):
    template_name = 'accounts/done.html'


class ConfirmPassword(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/confirm.html'
    success_url = reverse_lazy('accounts:complete')


class Complete(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/complete.html'

accounts/templates/accounts/complete.html
{% extends 'base.html' %}
{% block body %}
    <p>you can login</p>
{% endblock %}

accounts/templates/accounts/confirm.html
{% extends 'base.html' %}
{% block body %}
    <form method="post" action="">
        {% if validlink %}
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">reset</button>
        {% endif %}
    </form>
{% endblock %}

accounts/templates/accounts/done.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <p>check your email to reset password</p>
    </div>
{% endblock %}

accounts/templates/accounts/link.html
click link to reset password
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_done' uidb64=uid token=token %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    <a href="{% url 'accounts:reset' %}"><p>forget password?</p></a>

{% endblock body %}

accounts/templates/accounts/login_phone.html
{% extends 'base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
    <button type="submit">send code</button>
    </form>
{% endblock %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
    <button type="submit">change</button>
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="clo-6">
            <img src="{{ profile.image.url }}" style="height: 200px; width: 200px;">
        </div>
        <div class="col-6">
            <div class="card">
                        <table>
            <tr>
                <th>
                    user : {{ profile.user.username}}
                </th>
            </tr>
            <tr>
                <th>
                    name : {{ profile.user.first_name }}
                </th>
            </tr>
            <tr>
                <th>
                    email : {{ profile.user.email }}
                </th>
            </tr>
            </table>
            <a href={% url 'accounts:user_update' %}>update user</a>
            <a href={% url 'accounts:change_password' %}>change password</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/register_style.css' %}">
{% endblock %}
{% block body %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">create</button>
    </form>
{% endblock body %}

accounts/templates/accounts/reset.html
{% extends 'base.html' %}
{% block body %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form }}
        <button type="submit">send email</button>
    </form>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block title%}Update User{% endblock %}
{% block body %}
    <form method="post">
    {% csrf_token %}
        {{ form }}
        {{ profile_form }}
    <button type="submit">update</button>
    </form>
{% endblock %}

accounts/templates/accounts/verify_sms.html
{% extends 'bse.html' %}
{% block body %}
    <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">login</button>
    </form>
{% endblock %}