accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name='user_update'),
    path('ch_password/', views.change_password, name='change_password'),
    path('login_phone/', views.login_phone, name='login_phone'),
    path('verify_sms/', views.verify_sms, name='verify_sms'),
    path('active/', views.RegisterEmail.as_view(), name='active'),
    path('reset/', views.ResetPassword.as_view(), name='reset'),
    path('reset/done', views.DonePassword.as_view(), name='reset_done'),
    path('confirm/<uidb64>/<token>/', views.ConfirmPassword.as_view(), name='password_reset_done'),
    path('confrim/done/', views.Complete.as_view(), name='complete'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.card, name='card'),
    path('add_cart/<int:id>', views.add_cart, name='add_cart'),
    path('remove_cart/<int:id>', views.remove_cart, name='remove_cart'),
    path('add_quantity/<int:id>', views.add_quantity, name='add_quantity'),
    path('remove_quantity/<int:id>', views.remove_quantity, name='remove_quantity'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('category/<slug>/<int:id>/', views.products, name='category'),
    path('details/<int:id>/', views.products_details, name='products_details'),
    path('like/<int:id>', views.product_like, name='product_like'),
    path('unlike/<int:id>', views.product_unlike, name='product_unlike'),
    path('comment/<int:id>', views.comment, name='comment'),
    path('reply/<int:id>/<int:text_id>', views.comment_reply, name='comment_reply'),
    path('comment_like/<int:id>', views.comment_likes, name='comments_likes'),
    path('search/', views.product_search, name='product_search'),
    path('contact_us/', views.contact_us, name='contact_us'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls', namespace='home')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('order/', include('order.urls', namespace='order'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.
                                                                                           MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}
    {% endblock title %}
    </title>
    {% block css %}{% endblock css %}
</head>
<body>
{% include 'message.html' %}
{% include 'navbar.html' %}
{% block body %}
{% endblock body %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/message.html
{% if messages %}
    {% for mes in messages %}
        <h3>{{ mes }}</h3>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href={% url 'home:products' %}>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url 'accounts:register' %}>register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href={% url 'home:contact_us' %}>contact us</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href={% url 'accounts:logout' %}>Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url 'accounts:profile' %}>profile</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href={% url 'accounts:login' %}>Login</a>
        </li>
         {% endif %}
      </ul>
    </div>
  </div>
</nav>